name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *" # a cada 5 horas
  workflow_dispatch:

# ðŸ‘‡ Adicionado para garantir permissÃµes de escrita
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Gera Snake
        uses: Platane/snk@v3
        with:
          github_user_name: MarcosPaulosd
          outputs: dist

      - name: Confirma status do git
        run: git status

      - name: Faz push das mudanÃ§as
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: main

      - name: Publica no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # ðŸ”„ Usa o mesmo PAT_TOKEN aqui tambÃ©m



